site_name: rtacpy
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          paths: [rtacpy]
          options:
            docstring_style: sphinx
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - mdx_math